
"""
https://projecteuler.net/problem=2

Even Fibonacci numbers

Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def main():
    max_sum = 4_000_000

    before_last = 1
    last = 2

    total = 3
    even_sum = 2

    while total < max_sum:
        last += before_last
        before_last = last - before_last
        total += last
        if last % 2 == 0:
            even_sum += last

    print(f'Answer: {str(even_sum)}')

if __name__ == "__main__":
    main()